import {
  DashboardOutlined,
  ShoppingCartOutlined,
  ShoppingOutlined,
  UserOutlined,
  PictureOutlined,
  GiftOutlined,
  ShopOutlined,
  TeamOutlined,
  MailOutlined,
  SettingOutlined,
  MobileOutlined,
  ProfileOutlined,
} from "@ant-design/icons";
import { APP_PREFIX_PATH } from "configs/AppConfig";

const dashBoardNavTree = [
  {
    key: "basic",
    path: `${APP_PREFIX_PATH}/basic`,
    title: "основные",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "basic-dashboard",
        path: `${APP_PREFIX_PATH}/basic`,
        title: "Дашбоард",
        icon: DashboardOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-catalog",
        path: `${APP_PREFIX_PATH}/basic/catalog`,
        title: "Каталог",
        icon: ShoppingCartOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "basic-catalog-product",
            path: `${APP_PREFIX_PATH}/basic/catalog/product`,
            title: "Товары",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "basic-catalog-category",
            path: `${APP_PREFIX_PATH}/basic/catalog/category`,
            title: "Категории",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "basic-catalog-collection",
            path: `${APP_PREFIX_PATH}/basic/catalog/collection`,
            title: "Коллекции",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "basic-catalog-combo",
            path: `${APP_PREFIX_PATH}/basic/catalog/combo`,
            title: "Комбо",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "basic-orders",
        path: `${APP_PREFIX_PATH}/basic/orders`,
        title: "Заказы",
        icon: ShoppingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-clients",
        path: `${APP_PREFIX_PATH}/basic/clients`,
        title: "Клиенты",
        icon: UserOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "basic-clients-list",
            path: `${APP_PREFIX_PATH}/basic/clients/list`,
            title: "Список клиентов",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "basic-clients-group",
            path: `${APP_PREFIX_PATH}/basic/clients/group`,
            title: "Группа клиентов",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "basic-banners",
        path: `${APP_PREFIX_PATH}/basic/banners`,
        title: "Баннеры",
        icon: PictureOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-promo",
        path: `${APP_PREFIX_PATH}/basic/promo`,
        title: "Промокоды",
        icon: GiftOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-offline",
        path: `${APP_PREFIX_PATH}/basic/offline`,
        title: "Оффлайн точки",
        icon: ShopOutlined,
        breadcrumb: false,
        submenu: [
          {
            key: "basic-offline-address",
            path: `${APP_PREFIX_PATH}/basic/offline/address`,
            title: "Адреса",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
          {
            key: "basic-offline-geofences",
            path: `${APP_PREFIX_PATH}/basic/offline/geofences`,
            title: "Геозоны",
            icon: "",
            breadcrumb: false,
            submenu: [],
          },
        ],
      },
      {
        key: "basic-promo",
        path: `${APP_PREFIX_PATH}/basic/promo`,
        title: "Сотрудники",
        icon: TeamOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "basic-mail",
        path: `${APP_PREFIX_PATH}/basic/mail`,
        title: "Рассылки",
        icon: MailOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
  {
    key: "systemic",
    path: `${APP_PREFIX_PATH}/systemic`,
    title: "Системные",
    icon: "",
    breadcrumb: false,
    submenu: [
      {
        key: "systemic-settings",
        path: `${APP_PREFIX_PATH}/systemic/settings`,
        title: "Настройки",
        icon: SettingOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "systemic-mobile",
        path: `${APP_PREFIX_PATH}/systemic/mobile`,
        title: "Мобильное приложение",
        icon: MobileOutlined,
        breadcrumb: false,
        submenu: [],
      },
      {
        key: "systemic-logs",
        path: `${APP_PREFIX_PATH}/systemic/logs`,
        title: "Логи",
        icon: ProfileOutlined,
        breadcrumb: false,
        submenu: [],
      },
    ],
  },
];

const navigationConfig = [...dashBoardNavTree];

export default navigationConfig;
